### ISSUE TITLE
Handle Authentication Errors in useLoginWithEmailAndPassword

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#121]
**Title:** Handle Authentication Errors in `useLoginWithEmailAndPassword`

**Description:**
This GitHub issue is created to enhance the error handling in the `useLoginWithEmailAndPassword` function located in the hooks folder. The goal is to handle specific status codes and emit proper error messages using the `dispatchAPIError` function. Additionally, the issue covers the navigation of users to the dashboard (`'/dashboard'`) upon successful sign-in.

**Tasks:**
1. **Handle Code 400 (Bad Request):**
   - [ ] Implement error handling for the status code 400, which indicates that the email and password are required but not provided.
   - [ ] Emit a user-friendly error message using the `dispatchAPIError` function to inform the user about the missing email and password.

2. **Handle Code 404 (Not Found):**
   - [ ] Address the status code 404, which suggests that there is no such user with the provided email.
   - [ ] Redirect the user to the signup page to encourage them to create a new account.

3. **Handle Code 401 (Unauthorized):**
   - [ ] Implement error handling for the status code 401, which indicates that the provided password is incorrect.
   - [ ] Prompt the user to try again with the correct password.

4. **Handle Code 429 (Too Many Requests):**
   - [ ] Address the status code 429, which signifies that there are too many active sessions.
   - [ ] Inform the user to wait until other sessions are logged out before attempting to log in.

5. **Successful Sign-In Navigation:**
   - [ ] Once the user successfully logs in, navigate them to the dashboard (`'/dashboard'`).
   - [ ] Ensure that the navigation occurs seamlessly and redirects the user to the appropriate page.

**Additional Information:**
- Proper error handling enhances the user experience by providing clear and informative error messages.
- Successful sign-ins should smoothly transition the user to the dashboard, maintaining a positive user journey.

Upon successful implementation of this issue, the `useLoginWithEmailAndPassword` function will handle status codes 400, 404, 401, and 429 correctly, emitting appropriate error messages using `dispatchAPIError`, and navigate users to the dashboard when sign-in is successful.

**Comment by SySagar** [comment]
Can I work on this?

**Comment by prasenjeet-symon** [comment]
> Can I work on this?

Yes absolutely. Please make sure to emit the `errorType: APIErrorType.EmailPasswordLoginView` with human-readable error message.

**Comment by sandheep45** [comment]
@prasenjeet-symon I would like to suggest to handle error at the axios level and pass customised error to custom hooks. This approach would provide us a better way to debug. Additionally, I would also like to suggest to use some kind of logger at the axios level as well

**Comment by prasenjeet-symon** [comment]
Can you explain it in more detail with some code examples.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by prasenjeet-symon** [comment]
> @prasenjeet-symon I would like to suggest to handle error at the axios level and pass customised error to custom hooks. This approach would provide us a better way to debug. Additionally, I would also like to suggest to use some kind of logger at the axios level as well


Here is my explanation of the error system design: 

let's break down the error handling and event emitting process for network calls using hooks.

1. **Error Handling:**
   
   - Each hook is related to a specific Axios function. These hooks have the capability to catch errors that may occur during network calls.

   - When an error occurs within a hook, it emits a universal DOM event known as `API_ERROR`. This event signifies any error related to network calls.

   - Anyone interested can listen to this `API_ERROR` event in the DOM. Typically, this is where a logging mechanism is implemented to record all errors.

   - The emitted error is properly formatted and contains information about its source of origin, which is the specific hook and context where the error occurred.

   - The error data structure might look like this:
     ```typescript
     export interface APIErrorEventData {
       errorType: APIErrorType; // Context of the error (hook address)
       message: any; // Original error message
     }
     ```

2. **Human-Readable Errors:**

   - In addition to emitting `API_ERROR`, hooks may also emit a special event called `API_ERROR_VIEW`. 

   - `API_ERROR_VIEW` event data has the same structure as `API_ERROR`, with an `errorType` and `message`. However, the `message` field contains a human-readable error message.

   - The purpose of emitting `API_ERROR_VIEW` is to make it easier for components to handle and display errors to users in a user-friendly way, such as showing a toast notification.

This approach separates the responsibility of error handling and presentation. Errors are initially emitted in a format suitable for logging and debugging (`API_ERROR`). Then, if needed, a second event (`API_ERROR_VIEW`) is emitted with a user-friendly error message for display in the UI.

This organization makes it easier to handle and present errors while keeping the original error information intact for debugging purposes.

**Comment by sandheep45** [comment]
For example in the code below, you can check whether the issue is related to request or response.

```js
// axiosConfig.js

import axios from 'axios';

const axiosInstance = axios.create({
  baseURL: 'https://api.example.com',
});

axiosInstance.interceptors.response.use(
  (response) => response,
  (error) => {
    if (error.response) {
      // Handle server errors (e.g., 500 Internal Server Error)
      console.error('Server Error:', error.response.data);
    } else if (error.request) {
      // Handle network errors (e.g., no internet connection)
      console.error('Network Error:', error.message);
    } else {
      // Something else went wrong
      console.error('An error occurred:', error.message);
    }
    return Promise.reject(error);
  }
);

export default axiosInstance;

```


Additionally, we are able to separate the layers which have their own particular concern. For example axios is the interface between frontend and backend while hooks should be used to implement frontend logic, it is not meant to handle error so it should be ideally handled at very root level where they are expected to happen (at the axios level).

I hope this makes sense to you

**Comment by sandheep45** [comment]
> > @prasenjeet-symon I would like to suggest to handle error at the axios level and pass customised error to custom hooks. This approach would provide us a better way to debug. Additionally, I would also like to suggest to use some kind of logger at the axios level as well
> 
> Here is my explanation of the error system design:
> 
> let's break down the error handling and event emitting process for network calls using hooks.
> 
> 1. **Error Handling:**
>    
>    * Each hook is related to a specific Axios function. These hooks have the capability to catch errors that may occur during network calls.
>    * When an error occurs within a hook, it emits a universal DOM event known as `API_ERROR`. This event signifies any error related to network calls.
>    * Anyone interested can listen to this `API_ERROR` event in the DOM. Typically, this is where a logging mechanism is implemented to record all errors.
>    * The emitted error is properly formatted and contains information about its source of origin, which is the specific hook and context where the error occurred.
>    * The error data structure might look like this:
>      ```ts
>      export interface APIErrorEventData {
>        errorType: APIErrorType; // Context of the error (hook address)
>        message: any; // Original error message
>      }
>      ```
> 2. **Human-Readable Errors:**
>    
>    * In addition to emitting `API_ERROR`, hooks may also emit a special event called `API_ERROR_VIEW`.
>    * `API_ERROR_VIEW` event data has the same structure as `API_ERROR`, with an `errorType` and `message`. However, the `message` field contains a human-readable error message.
>    * The purpose of emitting `API_ERROR_VIEW` is to make it easier for components to handle and display errors to users in a user-friendly way, such as showing a toast notification.
> 
> This approach separates the responsibility of error handling and presentation. Errors are initially emitted in a format suitable for logging and debugging (`API_ERROR`). Then, if needed, a second event (`API_ERROR_VIEW`) is emitted with a user-friendly error message for display in the UI.
> 
> This organization makes it easier to handle and present errors while keeping the original error information intact for debugging purposes.

See in the interface `APIErrorEventData` the message type is `any` which is not ideal. Instead of you can receive a known type like a string or an object with a message, that would make it easier at the component level

**Comment by prasenjeet-symon** [comment]
> > > @prasenjeet-symon I would like to suggest to handle error at the axios level and pass customised error to custom hooks. This approach would provide us a better way to debug. Additionally, I would also like to suggest to use some kind of logger at the axios level as well
> > 
> > 
> > Here is my explanation of the error system design:
> > let's break down the error handling and event emitting process for network calls using hooks.
> > 
> > 1. **Error Handling:**
> >    
> >    * Each hook is related to a specific Axios function. These hooks have the capability to catch errors that may occur during network calls.
> >    * When an error occurs within a hook, it emits a universal DOM event known as `API_ERROR`. This event signifies any error related to network calls.
> >    * Anyone interested can listen to this `API_ERROR` event in the DOM. Typically, this is where a logging mechanism is implemented to record all errors.
> >    * The emitted error is properly formatted and contains information about its source of origin, which is the specific hook and context where the error occurred.
> >    * The error data structure might look like this:
> >      ```ts
> >      export interface APIErrorEventData {
> >        errorType: APIErrorType; // Context of the error (hook address)
> >        message: any; // Original error message
> >      }
> >      ```
> > 2. **Human-Readable Errors:**
> >    
> >    * In addition to emitting `API_ERROR`, hooks may also emit a special event called `API_ERROR_VIEW`.
> >    * `API_ERROR_VIEW` event data has the same structure as `API_ERROR`, with an `errorType` and `message`. However, the `message` field contains a human-readable error message.
> >    * The purpose of emitting `API_ERROR_VIEW` is to make it easier for components to handle and display errors to users in a user-friendly way, such as showing a toast notification.
> > 
> > This approach separates the responsibility of error handling and presentation. Errors are initially emitted in a format suitable for logging and debugging (`API_ERROR`). Then, if needed, a second event (`API_ERROR_VIEW`) is emitted with a user-friendly error message for display in the UI.
> > This organization makes it easier to handle and present errors while keeping the original error information intact for debugging purposes.
> 
> See in the interface `APIErrorEventData` the message type is `any` which is not ideal. Instead of you can receive a known type like a string or an object with a message, that would make it easier at the component level

It is not the responsibility of the component to handle the error or to display it . That will be managed by dedicated component whose primary goal is to display the toast of error message ( just the string formatted correctly ).

**Comment by sandheep45** [comment]
> > For example in the code below, you can check whether the issue is related to request or response.
> > ```js
> > // axiosConfig.js
> > 
> > import axios from 'axios';
> > 
> > const axiosInstance = axios.create({
> >   baseURL: 'https://api.example.com',
> > });
> > 
> > axiosInstance.interceptors.response.use(
> >   (response) => response,
> >   (error) => {
> >     if (error.response) {
> >       // Handle server errors (e.g., 500 Internal Server Error)
> >       console.error('Server Error:', error.response.data);
> >     } else if (error.request) {
> >       // Handle network errors (e.g., no internet connection)
> >       console.error('Network Error:', error.message);
> >     } else {
> >       // Something else went wrong
> >       console.error('An error occurred:', error.message);
> >     }
> >     return Promise.reject(error);
> >   }
> > );
> > 
> > export default axiosInstance;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Additionally, we are able to separate the layers which have their own particular concern. For example axios is the interface between frontend and backend while hooks should be used to implement frontend logic, it is not meant to handle error so it should be ideally handled at very root level where they are expected to happen (at the axios level).
> > I hope this makes sense
> 
> We are doing the same thing and more but at a single location. Please let me know your thought

As of my knowledge and experience, **separation of concern** is something which should be implemented any where possible. When a project becomes bigger and complex, debugging and bug fixes also increases accordingly. That's why I am suggesting not to deal more than one aspects at a single level

**Comment by prasenjeet-symon** [comment]
axiosInstance.interceptors is not going to give us the context of the error ( where to look for the actual file address and hook name to trace it back ). Yes, you can get the URL and do the things but that is a long way.

**Comment by prasenjeet-symon** [comment]
```js 
export function useLoginWithEmailAndPassword(navigate: NavigateFunction): IHookLoginWithEmailAndPassword {
  const loginMutation = useMutation<AxiosResponse<any, any>, AxiosError, { email: string; password: string }, unknown>(
    (inputData) => loginWithEmailPassword(inputData.email, inputData.password),
    {
      onError: (error) => {
        dispatchAPIError({
          errorType: APIErrorType.EmailPasswordLogin,
          message: error,
        });
      },
      onSuccess: (data) => {
      },
    },
  );

  const login = async (email: string, password: string) => {
    try {
      await loginMutation.mutateAsync({ email, password });
    } catch (error: any) {
      dispatchAPIError({
        errorType: APIErrorType.EmailPasswordLogin,
        message: error,
      });
    }
  };

  return { login, isLoading: loginMutation.isLoading };
}
``` 

Okay to better understand my points let us consider this hook. Can you see the `NavigateFunction` attribute? You can receive the context of the component directly in the hook , it will let you do the things like on error manage the proper navigation and also on success manage the proper navigation . User of the hook do not have to think about this complexity. They just have to use it .  But this cannot be achieved using the axios level error management.

**Comment by sandheep45** [comment]
Mark the logs at axios level and hook level in the image below

![image](https://github.com/prasenjeet-symon/intellectia/assets/105055197/64f1cd31-93cb-4b7f-9784-2a898b9eff5a)

what i meant by handling error at axios level doing what i have done in the `catch` block in the image below (this screenshot is  from the `api.ts` file )
![image](https://github.com/prasenjeet-symon/intellectia/assets/105055197/caa198af-292c-49ef-a8b5-707ba2736163)


this is from `authentication.hook.ts` file
![image](https://github.com/prasenjeet-symon/intellectia/assets/105055197/f3639b9f-cb19-4b3a-a409-6ec8364fc98c)

**Comment by prasenjeet-symon** [comment]
@sandheep45 I have made some changes please check the latest changes. Run the client and on the login page click the login button and check the console. Also, check the `apiErrorManager.ts` located in the API folder.

**Comment by prasenjeet-symon** [comment]
@SySagar Waiting for your PR. You can comment  your progress here. If facing any problems or need help just let us know. Thanks

**Comment by prasenjeet-symon** [comment]
![Screenshot 2023-10-08 093903](https://github.com/prasenjeet-symon/intellectia/assets/70169921/3557306e-3710-42ca-bc27-5571bd45a3d5)

@sandheep45  This is why we decided to use event-based error handling. Network error management is decoupled from the component. It is the responsibility of the react-query hook and `App.tsx` file with just a few lines of code.
