### ISSUE TITLE
Convert Cat's Moon Journey Markdown to JSON

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#146]
**Title**: Convert Cat's Moon Journey Markdown to JSON

**Description**:
This GitHub issue aims to create a function that converts a specific Markdown file, describing a cat's adventure to the moon, into JSON format. The goal is to extract and store the metadata related to this specific story in a structured format.

**Tasks**:
1. **Implement `markdownToJSON` Function**:
   - [ ] Create a function named `markdownToJSON` in the `seeder/utils.ts` file.
   - [ ] This function should read the specific Markdown file located in the assets folder, which describes the cat's journey to the moon.
   - [ ] Extract metadata such as `title`, `subTitle`, and `coverImage` from the YAML front matter of the Markdown file.
   - [ ] Convert the content of the Markdown file to both Markdown (`markdownContent`) and HTML (`htmlContent`) formats.
   - [ ] Construct the `coverImage` URL using the relative URL and the media path specified in the `server.ts` file.
   - [ ] Return the extracted metadata in JSON format as described below:

   ```json
   {
     "title": "The Pawsome Moon Adventure of Whiskers the Cat 🌕",
     "subTitle": "A whimsical tale of feline curiosity",
     "coverImage": "/assets/cat_moon.jpg",
     "markdownContent": "Content in Markdown format...",
     "htmlContent": "<p>Content in HTML format...</p>"
   }
   ```

**Acceptance Criteria**:
- The `markdownToJSON` function is successfully implemented.
- The function reads the specific Markdown file and extracts its metadata and content.
- The `coverImage` URL is constructed using the relative URL and the media path from `server.ts`.
- The extracted metadata is returned in the specified JSON format.

**Additional Information**:
- This function is designed to parse a specific Markdown file describing the cat's moon journey and convert it into structured JSON for storage and retrieval.
- The issue should be considered resolved once all tasks are completed, and the function has been successfully tested.

**Comment by DustyDogCodex** [comment]
Hi @prasenjeet-symon ,

Hope you are doing well! If no one has been assigned this issue, I would like to work on it for you.

Thanks!

**Comment by prasenjeet-symon** [comment]
Assigned successfully

**Comment by DustyDogCodex** [comment]
Hi @prasenjeet-symon ,

Hope you are doing well! I have submitted a PR that will close this issue. Please let me know if you need any additional changes!

Cheers!
