### ISSUE TITLE
 Implement Zod Validation for Adding Multiple Articles to an Article Series

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#184]
**Title**: Implement Zod Validation for Adding Multiple Articles to an Article Series

**Description**:
This GitHub issue aims to enhance the validation process for adding multiple articles to an article series within the `/user/article_series/:id/articles` route. The task involves implementing Zod validation to ensure the validity of the `id` parameter and the array of `articles` IDs. This improvement provides a more robust and structured validation approach, improving the overall quality of the code.

**Tasks**:
1. **Implement Zod Validation**:
   - [ ] Implement Zod validation for the `/user/article_series/:id/articles` route to validate the `id` parameter.
   - [ ] Define the validation logic using Zod to ensure the `id` parameter is required and cannot be 0.

2. **Array Validation**:
   - [ ] Implement Zod validation for the `articles` array to ensure it contains valid article IDs.
   - [ ] Verify that the `articles` array contains only numbers.

**Acceptance Criteria**:
- The `/user/article_series/:id/articles` route successfully implements Zod validation for the `id` parameter.
- The `id` validation ensures it is required and cannot be 0.
- The route implements Zod validation for the `articles` array.
- The `articles` validation ensures it contains only valid article IDs represented as numbers.

**Additional Information**:
- Implementing Zod validation enhances the reliability and maintainability of the code.
- The use of structured validation techniques provides a better user experience and minimizes errors.
- This enhancement contributes to the overall codebase quality.

**Comment by Sibindra** [comment]
@prasenjeet-symon  hey I am interested in this issue and I can help solve it I am just not sure why I have 404 not found issue on `/user` route. 
<img width="1178" alt="Screenshot 2023-10-14 at 8 31 29 PM" src="https://github.com/prasenjeet-symon/intellectia/assets/59206903/cb42c028-4207-4b6f-9daa-db08e5540d41">

**Comment by prasenjeet-symon** [comment]
> @prasenjeet-symon hey I am interested in this issue and I can help solve it I am just not sure why I have 404 not found issue on `/user` route. <img alt="Screenshot 2023-10-14 at 8 31 29 PM" width="1178" src="https://user-images.githubusercontent.com/59206903/275237776-cb42c028-4207-4b6f-9daa-db08e5540d41.png">

It looks like a client side route . Then we have not implemented that route yet . This issue is related to the server side . Please use the POSTMAN for the testing this route . I am assigning you to this issue. Need more help just ping anyone on the discord. Thanks

**Comment by prasenjeet-symon** [comment]
@Sibindra If you need help or got stuck note that you can ask us your bugs on Discord or simply comment here. Thanks

**Comment by Sibindra** [comment]
@prasenjeet-symon I may need some help but I have yet to checkout the new postman documentation. I will get back after checking out the docs and trying it out again

**Comment by sparsh-18** [comment]
If this issue is still open and if no one is working on it, can it be assigned to me? @prasenjeet-symon

**Comment by prasenjeet-symon** [comment]
> If this issue is still open and if no one is working on it, can it be assigned to me? @prasenjeet-symon

Thank so showing interest but all the validation-related task is completed. I will release more issues shortly
