### ISSUE TITLE
Implement Zod Validation for Deleting Multiple Articles from an Article Series

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#185]
**Title**: Implement Zod Validation for Deleting Multiple Articles from an Article Series

**Description**:
This GitHub issue is dedicated to enhancing the validation process for deleting multiple articles from an article series within the `/user/article_series/:id/articles` route. The task involves implementing Zod validation to ensure the validity of the `id` parameter and the array of `articles` IDs. This improvement provides a structured validation approach to maintain data integrity and code quality.

**Tasks**:
1. **Implement Zod Validation for `id` Parameter**:
   - [ ] Implement Zod validation for the `id` parameter in the `/user/article_series/:id/articles` route.
   - [ ] Define the validation logic using Zod to require the `id` parameter and ensure it cannot be 0.

2. **Array Validation for `articles`**:
   - [ ] Implement Zod validation for the `articles` array to ensure it contains valid article IDs.
   - [ ] Verify that the `articles` array contains only numbers.

**Acceptance Criteria**:
- The `/user/article_series/:id/articles` route successfully implements Zod validation for the `id` parameter.
- The `id` validation ensures it is required and cannot be 0.
- Zod validation is implemented for the `articles` array.
- The `articles` validation ensures it contains only valid article IDs represented as numbers.

**Additional Information**:
- Implementing Zod validation improves data integrity and code quality.
- The structured validation approach contributes to better data handling and error prevention.
- This enhancement helps maintain a robust and reliable codebase.

**Comment by sparsh-18** [comment]
Hi, this looks similar to the validator we created today. May I please work on this issue as well?

**Comment by prasenjeet-symon** [comment]
Assigned to you

**Comment by sparsh-18** [comment]
Hi, I need an input for this. As we are getting the body in this format, articles: number[], we cannot use an array of our existing idValidator as it expects an object with id.
Can we repeat the number validation inside arrayValidator such as
```
export const idArrayValidator = z.array(
    z
        .number({
            required_error: 'id is required',
            invalid_type_error: 'id must be a number',
        })
        .refine((value) => value !== 0, {
            message: 'id must not be equal to 0',
        }),
);
```
or can use something like this if(req.body.articles is array) req.body.articles.forEach(article => idValidator))

**Comment by prasenjeet-symon** [comment]
@sparsh-18 I think we can use idArrayValidator

**Comment by prasenjeet-symon** [comment]
> z
>         .number({
>             required_error: 'id is required',
>             invalid_type_error: 'id must be a number',
>         })
>         .refine((value) => value !== 0, {
>             message: 'id must not be equal to 0',
>         })

Also reuse the id validator already created

**Comment by sparsh-18** [comment]
> > z
> > .number({
> > required_error: 'id is required',
> > invalid_type_error: 'id must be a number',
> > })
> > .refine((value) => value !== 0, {
> > message: 'id must not be equal to 0',
> > })
> 
> Also reuse the id validator already created

actually this is where the problem is coming, the idValidator expects an object with field id, but we have to validate an array of ids.

**Comment by prasenjeet-symon** [comment]
@sparsh-18 Then create total new one that validate array of ids .

**Comment by sparsh-18** [comment]
HI @prasenjeet-symon please refer the [PR](https://github.com/prasenjeet-symon/intellectia/pull/198)
