### ISSUE TITLE
Set Up "intellectia" React Project with Vite

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#77]
**Title**: Set Up "intellectia" React Project with Vite

**Description**:
This GitHub issue outlines the steps to set up a new React project named "intellectia" using the Vite build tool with the React template. Vite provides a fast and modern development environment for React applications.

**Tasks**:
1. **Install Node.js and npm**:
   - [ ] Download and install Node.js and npm from the official website: [Node.js Official Website](https://nodejs.org/)
   - [ ] Verify the installation by running `node -v` and `npm -v` commands.

2. **Create a New Project**:
   - [ ] Open the terminal and run the command to create a new Vite project with the React template:
     ```bash
     npm init @vitejs/app intellectia --template react
     ```
   - [ ] Replace "intellectia" with the desired project name.

3. **Navigate to the Project Directory**:
   - [ ] Change to the project directory using the command:
     ```bash
     cd intellectia
     ```

4. **Install Dependencies**:
   - [ ] Run the following command to install project dependencies:
     ```bash
     npm install
     ```

5. **Start the Development Server**:
   - [ ] Start the Vite development server with the following command:
     ```bash
     npm run dev
     ```
   - [ ] Confirm that the application is accessible at `http://localhost:3000/`.

6. **Open in Your Browser**:
   - [ ] Open a web browser and navigate to `http://localhost:3000/` to ensure the React application is running.

7. **Start Coding**:
   - [ ] Begin editing React code within the `src` directory.
   - [ ] Confirm that changes are reflected in real-time due to Vite's hot module replacement (HMR).

8. **Build for Production**:
   - [ ] When ready for production, build the React app using:
     ```bash
     npm run build
     ```
   - [ ] Verify that a production-ready build is available in the `dist` directory.

**Acceptance Criteria**:
- This GitHub issue should serve as a comprehensive guide for setting up the "intellectia" React project using Vite.
- All tasks should be documented and marked as [ ] or [x] as appropriate.
- The steps provided should be clear and enable users to successfully create the "intellectia" React project with Vite.
- The issue should be considered resolved once all tasks are completed and verified.

**Additional Information**:
- If you encounter any issues or have questions during the setup process, please don't hesitate to ask for assistance.
