### ISSUE TITLE
Add React Query to React Project with Professional Directory Structure

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#78]
**Title**: Add React Query to React Project with Professional Directory Structure

**Description**:
This GitHub issue outlines the steps to integrate React Query into a React project while maintaining a professional directory structure. React Query is a powerful library for managing data fetching and state management in React applications.

**Tasks**:
1. **Install React Query**:
   - [ ] Install React Query and its dev tools as project dependencies:
     ```bash
     npm install react-query react-query/devtools
     ```

2. **Directory Structure**:
   - [ ] Organize the project directory structure following a professional pattern. The suggested structure is:
     ```
     my-react-app/
     |-- src/
     |   |-- components/       # React components
     |   |-- pages/            # Page components
     |   |-- api/              # API-related logic
     |   |-- hooks/            # Custom hooks
     |   |-- utils/            # Utility functions
     |-- App.js                # App component
     |-- index.js              # Entry point
     ```

3. **Create React Query Configuration File**:
   - [ ] Inside the `src` directory, create a file named `react-query.js` to hold the React Query configuration. The file should export `queryClient` and `QueryClientProvider`.

4. **Implement React Query**:
   - [ ] Create an API-related file, such as `api.js`, inside the `src/api` directory.
   - [ ] Implement a function for fetching data from an API in `api.js`. For example, `fetchData`.
   - [ ] Use React Query's `useQuery` hook to fetch data from the API in your components.

5. **Use React Query Provider**:
   - [ ] In your `index.js` file, wrap your app with the `QueryClientProvider` to provide the React Query context to your components.

6. **Run Your React App**:
   - [ ] Start your development server with the command `npm run dev`. Verify that your React app is available at `http://localhost:3000/`, utilizing React Query for data fetching and caching.

**Acceptance Criteria**:
- This GitHub issue should serve as a guide for integrating React Query into a React project with a professional directory structure.
- All tasks should be documented and marked as [ ] or [x] as appropriate.
- The steps provided should be clear and enable users to successfully integrate React Query into their project with a professional directory structure.
- The issue should be considered resolved once all tasks are completed and verified.

**Additional Information**:
- If you encounter any issues or have questions during the integration process, please provide updates or seek assistance as needed.
