### ISSUE TITLE
 Integrate Material-UI (MUI) into "intellectia" React Client with Default Dark Theme

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#81]
**Title**: Integrate Material-UI (MUI) into "intellectia" React Client with Default Dark Theme

**Description**:
This GitHub issue serves as a guide to integrate Material-UI (MUI) into the "intellectia" React client while applying a default dark theme. This integration allows the utilization of Material-UI components and theming for enhanced user interface design with a dark theme by default.

**Tasks**:
1. **Install Material-UI Packages**:
   - [ ] Install the essential Material-UI packages, including core components and icons, as project dependencies. Execute the following command within the project directory:
     ```bash
     npm install @mui/material @emotion/react @emotion/styled
     ```
     
   - [ ] Additionally, install Material-UI icons using the following command:
     ```bash
     npm install @mui/icons-material
     ```

3. **Wrap the App with Theme Provider**:
   - [ ] Integrate Material-UI theming by wrapping the application with the Material-UI ThemeProvider.
   
   - [ ] Configure the ThemeProvider to use a default dark theme by importing and applying it as follows:
     ```javascript
     // src/index.js
     import React from 'react';
     import ReactDOM from 'react-dom';
     import { ThemeProvider, createTheme } from '@mui/material/styles';
     import App from './App'; // Import your main App component
     
     // Define the default dark theme
     const theme = createTheme({
       palette: {
         mode: 'dark', // Apply dark mode by default
       },
       // Add more theme customization options as needed
     });
     
     ReactDOM.render(
       <ThemeProvider theme={theme}>
         <App />
       </ThemeProvider>,
       document.getElementById('root')
     );
     ```

**Acceptance Criteria**:
- This GitHub issue provides a comprehensive guide for integrating Material-UI into the "intellectia" React client with a default dark theme.
- All tasks are documented and clearly marked as [ ] or [x] to track progress.
- Successful integration of Material-UI components and icons into the project.
- Application of a default dark theme using the Material-UI ThemeProvider.
- The GitHub issue is considered resolved when all tasks are completed and validated.

**Additional Information**:
- If you encounter any challenges or have questions during the integration process, please don't hesitate to provide updates or seek assistance.
- The integration of Material-UI enhances the user interface of the "intellectia" React client, offering a dark-themed appearance by default.

**Comment by sandheep45** [comment]
I would like to suggest shadcn ui instead of mui.

**Comment by prasenjeet-symon** [comment]
> I would like to suggest shadcn ui instead of mui.

Okay! Please create a new issue regarding this
