### ISSUE TITLE
Create Function to Generate Intellectia Topics

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#98]
**Title**: Create Function to Generate Intellectia Topics

**Description**:
This GitHub issue is created to outline the development of a function that generates the necessary topics to be used in the Intellectia app. The function's purpose is to ensure that the app has a predefined set of topics available for users.

**Tasks**:
1. **Database Interaction**:
   - [ ] Fetch all existing topics from the database.

2. **Load Topics from JSON File**:
   - [ ] Load topic data from a JSON file located in the assets folder. The JSON file format should be as follows:
     ```json
     {
       "topics": ["Topic 1", "Topic 2", "Topic 3"]
     }
     ```

3. **Identify New Topics**:
   - [ ] Compare the topics loaded from the JSON file with the existing topics in the database.
   - [ ] Identify and extract any new topics that are not present in the database.

4. **Create New Topics in the Database**:
   - [ ] For each new topic identified, create a corresponding record in the database.

5. **Runtime Execution**:
   - [ ] Ensure that this function runs automatically on server startup to keep the topics up-to-date.

6. **Database Update Strategy**:
   - [ ] Implement a strategy that does not delete existing topics from the database or the JSON file. Only new topics should be added.

**Acceptance Criteria**:
- The function successfully fetches existing topics from the database.
- The function loads topics from the JSON file.
- It identifies new topics that are not already in the database.
- New topics are added to the database without deleting existing ones.
- The function is integrated into the server and runs on startup.

**Additional Information**:
- This function is essential for maintaining an up-to-date list of topics in the Intellectia app and should be executed on server startup to ensure that new topics are available to users.

**Comment by prasenjeet-symon** [comment]
Check the utils file of the server for the function `createIntellectiaTopics`
