### ISSUE TITLE
Add Topics JSON to Server Assets Folder

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#99]
**Title**: Add Topics JSON to Server Assets Folder

**Description**:
This GitHub issue is created to document the task of adding a JSON file containing all the topics related to the project to the assets folder of the server. Having this JSON file will facilitate the management and synchronization of topics across the Intellectia app.

**Tasks**:
1. **Create Topics JSON File**:
   - [ ] Create a JSON file named `topics.json` with the following structure:
     ```json
     {
       "topics": ["Topic 1", "Topic 2", "Topic 3"]
     }
     ```

2. **Populate JSON File**:
   - [ ] Populate the `topics.json` file with an array of topic strings, ensuring that it includes all topics that are part of the project's scope.

3. **Add File to Assets Folder**:
   - [ ] Place the `topics.json` file in the assets folder of the server so that it is accessible to the application.

**Acceptance Criteria**:
- The `topics.json` file is created with the specified JSON structure.
- The JSON file includes all topics related to the Intellectia project.
- The `topics.json` file is successfully added to the assets folder of the server.

**Additional Information**:
- The inclusion of this JSON file in the server's assets folder will simplify the management of topics in the Intellectia app and enable efficient synchronization with the front-end components as needed.

**Comment by gagan-28deep** [comment]
Please assign it to me.
remote: Permission to prasenjeet-symon/intellectia.git denied to gagan-28deep.

I am getting this error.
I can help with the issue.

**Comment by prasenjeet-symon** [comment]
@gagan-28deep I have assigned you the issue. Waiting for the PR. Thanks

**Comment by prasenjeet-symon** [comment]
> remote: Permission to prasenjeet-symon/intellectia.git denied to gagan-28deep.
> 
> I am getting this error.

Please fork the repo and then submit the PR. Read more at https://github.com/prasenjeet-symon/intellectia/blob/main/CONTRIBUTING.md

**Comment by gagan-28deep** [comment]
I have created pr, if that is fine pls merge it, or let me know the changes.
I'll make the changes.

Thank You

**Comment by gagan-28deep** [comment]
Thank You for the opportunity. 
It was good to contribute, as it was my first time contributing to open source. I really hope I can contribute further also.

**Comment by prasenjeet-symon** [comment]
You're very welcome! We're delighted to have you contribute, We're looking forward to more contributions from you in the future.

If you found this experience valuable, we'd greatly appreciate it if you could give us a like or share your positive experience. It helps us a lot. Thank you again for your contribution! 😊👍
